name: schedulelist
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  # Local Database
  sqflite: ^2.3.0
  path: ^1.8.3
  # State Management & Utils
  provider: ^6.1.1
  intl: ^0.18.1
  image_picker: ^1.0.7
  # Untuk menyimpan gambar lokal
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/icon/logo_schedule.png
